name: CI-CD

on:
  push: 
     branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: checking source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortner-backend:latest .

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/url-shortner-backend:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: Pull image from docker hub
        run: docker pull url-shortner-backend:latest

      - name: Delete old container
        run: docker rum -f nodejs-app-container

      - name: Run docker container
        run: docker run -d -p ${{ env.DOCKER_PORT }}:${{ env.DOCKER_PORT }} -name nodejs-app-container url-shortner-backend
      