name: CI-CD

on:
  push: 
     branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checking source code
        uses: actions/checkout@v3
      - name: login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t url-shortner-backend .
      - name: Publish image to docker hub
        run: docker push url-shortner-backend:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull url-shortner-backend:latest
      - name: Delete old container
        run: docker rum -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p ${{env.DOCKER_PORT}}:${{env.DOCKER_PORT}} -name nodejs-app-container url-shortner-backend
      